### ISSUE TITLE
Experiment with binary op & ResNet9 seems to fail

### ISSUE THREAD

**Issue by YouCaiJun98** [jamesal1/NESgpu#1]
Hello, and THX for your inspiring repo!
I'm currently looking into BNN training with NES, and your repo really helps me a lot!
However, when I ran cifar10test.py (without any modification), I found that the logged reward tensor became nan within 10 epochs, and the accuracy displayed stuck at ~10%, which seems like a random guess. I wonder if it is the phenomenon you mentioned in README.md that BNNs are hard to train with NES, or how could I modify the script to get the accuracy higher?
Looking forward to your reply :)

**Comment by jamesal1** [comment]
the current cifar10test.py file doesn't use a binary network. It's also pretty hard to train cifar 10 using NES on normal weights, and I haven't gotten any really good results on it. I'd suggest sticking with MNIST if you want to try using BNN + NES.

**Comment by YouCaiJun98** [comment]
> the current cifar10test.py file doesn't use a binary network. It's also pretty hard to train cifar 10 using NES on normal weights, and I haven't gotten any really good results on it. I'd suggest sticking with MNIST if you want to try using BNN + NES.

Yes, I noticed that when I switched to other models such as SmallNet, where it raised a NotImplemented error. Then I tried to run the MNIST implementation and it looked fine. Anyway, THX for your help ;)
